name: ng2soyc
version: 0.0.2
description: GWT-inspired Story Of Your Compile CLI for Angular2
authors:
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/angular/ng2soyc.dart
environment:
  sdk: ">=1.11.1 <2.0.0"
dependencies:
  args: '^0.13.2'
  quiver: '^0.21.4'
  path: '^1.3.6'
dev_dependencies:
  test: '^0.12.3+9'
executables:
  ng2soyc: ng2soyc
